[packaging]
package_name = "shesh-azure-mgmt-devspaces"
package_nspkg = "shesh-azure-mgmt-nspkg"
package_pprint_name = "Devspaces Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
